version: '3.8'

services:
  video-processor:
    image: gabrielpi/video-processor:latest

    labels:
      - traefik.enable=true
      - traefik.http.routers.video-processor.rule=Host(`video.${DOMAIN_NAME}`)
      - traefik.http.routers.video-processor.tls=true
      - traefik.http.routers.video-processor.entrypoints=web,websecure
      - traefik.http.routers.video-processor.tls.certresolver=leresolver
      - traefik.http.services.video-processor.loadbalancer.server.port=5000
      - traefik.http.middlewares.video-auth.basicauth.users="admin:$$2y$$10$$hBcoTrigger"

    ports:
      - "5000:5000"

    volumes:
      - /root/n8n-videos:/app/downloads
      - /root/n8n-videos/cuts:/app/cuts
      - video_temp:/app/temp

    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - MAX_DOWNLOAD_SIZE=2GB
      - CLEANUP_INTERVAL=24h
      - ALLOWED_DOMAINS=youtube.com,youtu.be
      - LOG_LEVEL=INFO
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - WEBHOOK_BASE_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}

    networks:
      - n8n

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

volumes:
  video_temp:
    driver: local

networks:
  n8n:
    external: true
